### ISSUE TITLE
streams=kline_1w@@arr error: 2 - string indices must be integers

### ISSUE THREAD

**Issue by CryptoFuturesAU** [oliver-zehentleitner/unicorn-binance-websocket-api#102]
Hi, I'm running this code:

kline1w = binance_websocket_api_manager.create_stream('kline_1w', params.pair)   

and receive this error:

ERROR:root:BinanceWebSocketApiConnection->__enter__(eb542012-f537-40d2-9104-554cb139dcf8, ['kline_1w'], ['maticbtc']) connecting to wss://stream.binance.com:9443/stream?streams=maticbtc@kline_1w error: 2 - string indices must be integers

What is the solution? Thank you

**Comment by Flowelcat** [comment]
This is known bug and we working on it, check details on #98
