### ISSUE TITLE
pip cannot be installed

### ISSUE THREAD

**Issue by dare0047** [oliver-zehentleitner/unicorn-binance-websocket-api#108]
when running command "sudo apt install python3-pip" Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by oliver-zehentleitner** [comment]
What is the name of your OS?
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Installation

**Comment by dare0047** [comment]
OS is windows 10 but i use kali in VM

**Comment by oliver-zehentleitner** [comment]
Please google "kali linux Package python3-pip", you will find some guides to solve this!

**Comment by dare0047** [comment]
I have googled it and other me so much of them face this problem. Maybe my
repository will be out of date. Need to be updated
Anyway thank you for your help.
