### ISSUE TITLE
Unexpected ConnectionClosed in keepalive ping task

### ISSUE THREAD

**Issue by oliver-zehentleitner** [oliver-zehentleitner/unicorn-binance-websocket-api#11]
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x] Linux (include flavour)

#### Python Version Requirement
- [x] I am using Python 3.5.1 or above

#### Exact Python Version?
3.5.2
#### Pip Version?
pip 19.1
#### Description of your issue
The issue occurs in the dependency websockets and the issue is known: https://github.com/aaugustin/websockets/issues/551

During a lot of tests in the last week, i recognized this error only one time till now. I will observe this issue.

**Comment by bithon** [comment]
On 7 systems, each with 19 websockets and a transfer rate of ~30 GB/day, this error never happend again. I stopped using 3.5.2 and upgraded to 3.7.

**Comment by bithon** [comment]
Till someone tells me, this issue happens also on higher python versions, its closed...

**Comment by fsteckel** [comment]
Happened to me also on python version 3.7.5, pip 18.1, ubuntu 19.10 in a local docker container.

`
WARNING:websockets.protocol:Unexpected exception in keepalive ping task                                                      
Traceback (most recent call last):                                                                                           
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 984, in keepalive_ping                          
    ping_waiter = yield from self.ping()                                                                                     
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 583, in ping                                    
    yield from self.ensure_open()                                                                                            
  File "/usr/local/lib/python3.7/dist-packages/websockets/protocol.py", line 646, in ensure_open                             
    ) from self.transfer_data_exc                                                                                            
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal])
, no reason
`

**Comment by oliver-zehentleitner** [comment]
Can you provide some infos please:
- markets and channels you use to start the stream
- how often does it happen?
- version of the library
- does the error get catched and the stream restarts or does it stop?
- are you using the stream_buffer or do you provide a callback method/function?

thanks

**Comment by fsteckel** [comment]
- I am streaming all BTC related markets with channels depth and depth20. All streams are started separately and their ids kept in a list.

- This error happened three times in the last 5 days. 

- version 1.9.1

- The stream does restart, however I am unsure from the logs whether this is unicorns work or mine, as my wrapper also checks for status 'alive' and last heartbeat and subsequently restarts.

- I am using the stream buffer.

**Comment by oliver-zehentleitner** [comment]
Is it possible to share the docker container with me? Could help me, i can reproduce the error...

**Comment by oliver-zehentleitner** [comment]
Still receiving this error? Would like to investigate it ...

**Comment by fsteckel** [comment]
Yes. I have a logfile (from nohup) with several stream related errors that I cannot fully comprehend. Is there any way I can get this to you?

**Comment by oliver-zehentleitner** [comment]
Under the "leave a comment" box is written "Attach files by dragging & dropping, selecting or pasting them" ... just upload it here!

**Comment by oliver-zehentleitner** [comment]
>     * The stream does restart, however I am unsure from the logs whether this is unicorns work or mine, as my wrapper also checks for status 'alive' and last heartbeat and subsequently restarts.

My goal for this lib is, that the library is managing all restarts - if you find a scenario that doesn’t reconnect please report it to me!

**Comment by oliver-zehentleitner** [comment]
Can you test this branch please, its using websockets 8.1 instead of 7.0:
`pip install https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/tarball/websockets_bug --upgrade`

the lib got a lot of commits related to this issue, maybe its solved now.

**Comment by fsteckel** [comment]
> 
> 
> Under the "leave a comment" box is written "Attach files by dragging & dropping, selecting or pasting them" ... just upload it here!

Ok, I uploaded my log, there are a few other exceptions. I'll thus check out the afforementioned branch now. Thanks!

[nohup.log](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/4250665/nohup.log)

**Comment by oliver-zehentleitner** [comment]
In 1.10.0 I changed a lot of core code and in the meantime a fixed a few bugs (1.10.6).

I will go through your file! 

Thank you and good luck with ws 8.1!

**Comment by oliver-zehentleitner** [comment]
From which unicorn version is this log file? Still 1.9.1 or did you upgrade in the meantime?

A question, why are you creating one websocket per tradingpair? This is very inefficient, because the lib creates a thread for every stream you create and you get also overhead by the websocket connection itself. 

So with your script you create ~1000 threads. 

Since 1.10.0 its possible to create one stream for all kind of subscriptions, I put a lot of effort to make this possible :D

Maybe you want take a look at this example file: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_stream_everything.py

This screenshot is from a server of mine at hetzner (2,9 EUR) with one core an 2 GB RAM:
![Screenshot_20200225_174039](https://user-images.githubusercontent.com/47597331/75267210-3f12f600-57f6-11ea-9f57-8f8d960e466d.png)

**Comment by oliver-zehentleitner** [comment]
Hi!
The first error in the logs is fixed now, keepalive bug is the next in the logfiles. Not shure its a follow of the first bug or its from websockets lib. It also could be a problem with your internet connection:
` OSError - SSL handshake is taking longer than 60.0 seconds: aborting the connection`
That means that your internet con was gone since more than 60 seconds, websockets ping/pong game needs max 40 seconds for one cycle, so the messages logged before could be related to your network error or your system was bloated from all that threads. there are logs from more than 3500 threads so we can expect that a lot of threads are crashing at the same time and restart on high frequent.
i will release a new version soon.

**Comment by oliver-zehentleitner** [comment]
> Can you test this branch please, its using websockets 8.1 instead of 7.0:
> `pip install https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/tarball/websockets_bug --upgrade`

I added fixes for bugs you reported, please update the package!

**Comment by fsteckel** [comment]
Hey Oliver! First of all, thanks for the awesome support! Did not expect this level of involvement!

At first I did not seperate the streams the way I do now, but created one with all markets and streamtypes. Encountering the errors, I thought, maybe it would be more easily debuggable if I seperate them, so I did. Will change that back soon, but dont have the capacity now.
However I changed to your websockets_bug branch and it looks way better now. I still have to include the update from 15 hours ago. Still no errors since yesterday. Thanks very much!

**Comment by oliver-zehentleitner** [comment]
Your welcome! :)

Then i am going to remove the branch 'websocket_bug' and merge it with the `master` branch and prepare a new release.

Thanks for the feedback! Testing this lib is not easy and very time consuming to me. 

I will close this issue, but it can get open again if needed!

Best regards

**Comment by oliver-zehentleitner** [comment]
Changes are released in 1.11.0 together with support for jex.com
