### ISSUE TITLE
Add spot and futures testnet

### ISSUE THREAD

**Issue by oliver-zehentleitner** [oliver-zehentleitner/unicorn-binance-websocket-api#115]
https://dev.binance.vision/t/binance-testnet-links/99
```
Spot Testnet:
https://testnet.binance.vision/
wss://testnet.binance.vision/ws
wss://testnet.binance.vision/stream

Futures Testnet:
https://testnet.binancefuture.com
wss://stream.binancefuture.com
```

**Comment by opoet777** [comment]
hi, how to use binance future testnet?

**Comment by oliver-zehentleitner** [comment]
Hello!

Its not implemented atm!

**Comment by opoet777** [comment]
do you have any plan for it?

**Comment by oliver-zehentleitner** [comment]
I detected it today and posted it here as a reminder. Actually it could be done within 30 min if there is nothing special. 

Are you able to test it if I do the implementation?

**Comment by opoet777** [comment]
yes of cource

**Comment by oliver-zehentleitner** [comment]
I will try to do it this week! I post you here when its done.

**Comment by oliver-zehentleitner** [comment]
Can you test please: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/releases/tag/1.18.0

**Comment by oliver-zehentleitner** [comment]
BinanceWebSocketApiManager(exchange="binance.com-testnet")
BinanceWebSocketApiManager(exchange="binance.com-futures-testnet")

**Comment by opoet777** [comment]
thanks, i tested binance future testnet user data stream, its work perfect

**Comment by oliver-zehentleitner** [comment]
thanks for the report

If someone tests the spot testnet and has problems. please open new issue!
