### ISSUE TITLE
BinanceWebSocketApiManager.get_current_receiving_speed_global() - RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by rodrigomfw** [oliver-zehentleitner/unicorn-binance-websocket-api#123]
Hi,
can someone explain to me why this message shows up around 4 times a day?

ERROR:root:BinanceWebSocketApiManager.get_current_receiving_speed_global() - RuntimeError: dictionary changed size during iteration

I'm only using a stream with ~250 subscriptions.

This error has no impact on performance, the program keeps running without issues, but I would like to know what is the cause and how to stop the message from appearing.

**Comment by oliver-zehentleitner** [comment]
This is only used to measure the `highest_receiving_speed` and if the error is detected it just do nothing and get restarted within a second again.

Nothing to worry about, it will be removed from the logs within the next 1-2 releases.
