### ISSUE TITLE
Binance API Updates

### ISSUE THREAD

**Issue by oliver-zehentleitner** [oliver-zehentleitner/unicorn-binance-websocket-api#127]
**Is your feature request related to a problem? Please describe.**
https://binance-docs.github.io/apidocs/futures/en/#change-log

**Describe the solution you'd like**
Test the changes and make changes to the lib if needed:

> 2020-10-27
> 
> WEB SOCKET STREAM
> 
>     The maximum stream number that a single connection can listen to changes as 200.
> 
> 2020-10-10
> 
> WEBSOCKET
> 
>     New WebSocket streams <symbol>@compositeIndex for composite index symbol information.
>

**Comment by kimchirichie** [comment]
oh i hate they did this. i need to modify my code again 😫

**Comment by oliver-zehentleitner** [comment]
I added a wiki page to collect relevant endpoint settings: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Binance-websocket-endpoint-configuration-overview
