### ISSUE TITLE
Monitor Orders

### ISSUE THREAD

**Issue by ShayanFiroozi** [oliver-zehentleitner/unicorn-binance-websocket-api#129]
Hi,
How can i use his library to call a **callback** function when an **order**  is created/removed or etc....
Thank you.

**Comment by oliver-zehentleitner** [comment]
I would create a loop (thread) and check the stream_buffer. But you made it bold, so here is your answer:
1. create a callback function like this one: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_process_streams.py

2. use it: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html?highlight=process_stream_data

**Comment by ShayanFiroozi** [comment]
> I would create a loop (thread) and check the stream_buffer. But you made it bold, so here is your answer:
> 
> 1. create a callback function like this one: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_process_streams.py
> 2. use it: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html?highlight=process_stream_data

Thank you , you are the man !👍
