### ISSUE TITLE
Sorting userdata stream by E

### ISSUE THREAD

**Issue by tranceporter** [oliver-zehentleitner/unicorn-binance-websocket-api#135]
Hi,

Thanks for this amazing codebase. Works very well :)
I am curious to know if we are already sorting the userdata stream by E? I merely ask because Binance docs suggest this:

> User data stream payloads are not guaranteed to be in order during heavy periods; make sure to order your updates using E

[https://binance-docs.github.io/apidocs/futures/en/#user-data-streams](url)

I am trying to implement copy trading functionality and I have it mostly working, but when stop market order is executed (stop hit), I seem to get "stop market expired" followed by "new order in opposite direction of the trade" (so I had a long position open, thne a new order for sell is created). While this seems to work fine on the master account, when it gets copied to slave account, it actually executes the stop (so long position is stopped out), followed by copying of the new SELL order, thus opening a short position :)

Maybe it's an issue in my code, but just wanted to chekc if we are already sorting by the timestamp value in E out of the box :)
If not, is there any clean way of doing this once I subscribe to the stream? 

Thanks,
Shreyas

**Comment by oliver-zehentleitner** [comment]
hi! 

thank you!

no, the lib does not do any sorting! it receives a data record and puts it on the stream_buffer FIFO stack. With `pop_stream_data_from_stream_buffer()` you get the oldest entry from the stack or if empty `False`. But oldest means its from all items in the stack the longest remaining one!  

As the documentation says, they can guarantee it, so you have to collect and then sort. Do you store in a database? if you work with the saved data, you can do SELECT with `order by E` for example...

Best regards,
Oliver

**Comment by tranceporter** [comment]
Yeah looks like the sensible way to do is to dump into a relational
database and then sort it, and then process it for
copy trade. That will introduce more latency unfortunately. Currently the
copy trade relocated in a split second. So super fast. Need to have a bit
more think :)

**Comment by oliver-zehentleitner** [comment]
then create a stack with pandas and sort it after every entry...

**Comment by tranceporter** [comment]
Haha yeah. Not very sustainable IMO. Especially if the master account is a
scalp account, then I will have to make the E time stamp as primary key to
sort it automatically in the table. Will try it out as is to see how far I
can stretch it. Else switch to using sql express or similar databases

**Comment by oliver-zehentleitner** [comment]
Since the initial question (sorting) is answered i hope its ok to close the issue!

**Comment by tranceporter** [comment]
Yes no problem. Thank you :)
