### ISSUE TITLE
Working with timestamps

### ISSUE THREAD

**Issue by DrPaprikaa** [oliver-zehentleitner/unicorn-binance-websocket-api#138]
Hi,
Thank you for your amazing library !

I have a hard time converting timestamps to valid datetimes and wouldn't mind a bit of help. Here is what I'm doing :

1. Create a stream for orderbook depth via `create_stream()` with `depth20@100ms`
2. Fetch the lastest data from the stream via `oldest_stream_data_from_stream_buffer = binance_websocket_api_manager.pop_stream_data_from_stream_buffer()`
3. Get the timestamp of the lastest data using `oldest_stream_data_from_stream_buffer['last_update_id']`

This gives me a timestamp like `2046077850`. Fair enough, let's convert it to a datetime object :
`print(datetime.datetime.utcfromtimestamp(2046077850))` results in `2034-11-02 10:57:30`, which is nowhere near the current time. 

How can I have the correct datetime, with milliseconds ?

Sorry if this not fully related to this library, I can delete my issue as soon as it's resolved if you want.

DrPaprikaa

**Comment by oliver-zehentleitner** [comment]
Hi!
I guess you are working with milliseconds but expect to be working with seconds. Just do /1000 and try again.
Best regards,
Oliver

**Comment by DrPaprikaa** [comment]
Hi!
I already tried :
`print(datetime.datetime.utcfromtimestamp(2046077850))` gives `2034-11-02 10:57:30`
`print(datetime.datetime.utcfromtimestamp(2046077850/1000))` gives `1970-01-24 16:21:17.850000`

I'm a bit lost...

**Comment by jon4hz** [comment]
Take a look at this: https://stackoverflow.com/questions/18724037/datetime-unix-timestamp-contains-milliseconds#18724098

**Comment by oliver-zehentleitner** [comment]
oh, you are using the ID not the timestamp: `oldest_stream_data_from_stream_buffer['last_update_id']`

**Comment by DrPaprikaa** [comment]
Ok thanks my bad, `last_update_id` is not a timestamp :) I am using the [Partial Book Depth Stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams) which doesn't return any timestamp. But then, how can I know the timestamp of the data I'm receiving ? Trading is about timing, I need to know if the data I'm receiving is delayed !

**Comment by DrPaprikaa** [comment]
btw, `oldest_stream_data_from_stream_buffer` is confusing (from my perspective), since the 'oldest' in the name suggests that we retreive the oldest data and not the newest

**Comment by oliver-zehentleitner** [comment]
i dont work with depth... isnt there an event_time?

To know if the data you receive is delayed you can do 2 different things.
1. check the size of the stream_buffer
2. use stream_signals so know the status of the streams

actually its a FIFO stack and we do a pop(0) which should return the oldest entry from the stack....

**Comment by DrPaprikaa** [comment]
There is an `event_time` for the [Diff. Depth Stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#diff-depth-stream), but it's not what I need and is different than the [Partial Book Depth Stream](https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams), which only has an `lastUpdateId`.

Would you mind explaining how the size of the stream_buffer allows to know if the data is delayed ? By how much milliseconds ? I'm plotting the bids & asks in real time and I need to have the correct time labels.

> actually its a FIFO stack and we do a pop(0) which should return the oldest entry from the stack

If it's a [FIFO](https://stackoverflow.com/a/35031174/13490000), wouldn't a `pop(0)` get us the _newest_ entry ?

**Comment by oliver-zehentleitner** [comment]
not for that the stream_buffer doesnt help but if its not empty or almost empty you know there is a delay...

I think a pop() delivers the latest entry, a pop(0) delivers the oldest entrie... anyway. It seems there are faster and better ways to do so. https://docs.python.org/2/tutorial/datastructures.html#using-lists-as-queues

**Comment by oliver-zehentleitner** [comment]
Released: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/releases/tag/1.32.0
