### ISSUE TITLE
`stream_buffer_name` vs `stream_label` in `binance_websocket_api_manager.create_stream()`

### ISSUE THREAD

**Issue by xilopaint** [oliver-zehentleitner/unicorn-binance-websocket-api#140]
Could anyone explain me the difference between `stream_buffer_name` and `stream_label` parameters in `binance_websocket_api_manager.create_stream()`?

What's the point of having both parameters instead of only one of them?

**Comment by oliver-zehentleitner** [comment]
`stream_label` is the name/label you choose for the stream and can be used with `get_stream_id_by_label()` and is shown in `print_summary()` which helps you to identify it in the view and should be unique (one stream, one label)

`stream_buffer_name`  is the name of the buffer you want to use. you can use one buffer for all streams or just one buffer for one stream. for example you can create 2 streams to stream all trades. Since there are more than 1024 trading pairs, not all subscriptions fit into one stream, so you have to create 2 streams:
stream_label="trades_1" and stream_label="trades_2" but both use stream_buffer_name="trades"

**Comment by xilopaint** [comment]
> Since there are more than 1024 trading pairs, not all subscriptions fit into one stream

Thanks for the explanation. How many subscriptions fit into one stream?

**Comment by oliver-zehentleitner** [comment]
that depends on the exchange endpoint, i made an overview here: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Binance-websocket-endpoint-configuration-overview

**Comment by xilopaint** [comment]
> you can use one buffer for all streams or just one buffer for one stream.

Do I have better performance using just one buffer per stream or one buffer for all streams?

**Comment by oliver-zehentleitner** [comment]
Splitting them uses a little bit more RAM but i think it saves operation times and avoids threading locks. Only one stream at a time can write to the buffer - the more buffers the less locks...

**Comment by xilopaint** [comment]
> Splitting them uses a little bit more RAM but i think it saves operation times and avoids threading locks. Only one stream at a time can write to the buffer - the more buffers the less locks...

So is it generally preferable to split them, right?

**Comment by oliver-zehentleitner** [comment]
I think yes! But never tested this out.
https://medium.com/python-features/using-locks-to-prevent-data-races-in-threads-in-python-b03dfcfbadd6

**Comment by xilopaint** [comment]
One more question. `stream_buffer_name` can be `bool` or `str`. If it's set to `False` data is written to the default `stream_buffer` and if it's set to `True` data can be read via `pop_stream_data_from_stream_buffer(stream_id)`. In the latter case do we have separate `stream_buffer` without a name?

**Comment by oliver-zehentleitner** [comment]
yes

**Comment by xilopaint** [comment]
What happens if I unsubscribe from all channels and markets in a stream? An exception is returned or the library handle this situation?

**Comment by oliver-zehentleitner** [comment]
then its a stream (established websocket connection) without subscriptions... 

i suggest you try a few of the example files i prepared and play a little bit with the code... try and error. I think the initial question is answered i close this!
