### ISSUE TITLE
Allow to disable logging, or increase default logging to DEBUG

### ISSUE THREAD

**Issue by nisanb** [oliver-zehentleitner/unicorn-binance-websocket-api#146]
**Is your feature request related to a problem? Please describe.**
I'm using python logging to trace and debug my program. It's making it harder when all of BinanceWebSocketApiManager loggings are set by default to INFO, blowing my logging file :(

**Describe the solution you'd like**
..

**Describe alternatives you've considered**
I thought about manually removing them, but that's not a good option..

**Additional context**

**Comment by oliver-zehentleitner** [comment]
I never used it, but there is a way to split the logs of ubwa and your code:
https://stackoverflow.com/questions/58020019/how-to-separate-log-handlers-in-python

**Comment by oliver-zehentleitner** [comment]
Please feel free to reopen if needed.
