### ISSUE TITLE
ERROR:root:BinanceWebSocketApiRestclient._request() - error_msg: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by amaioli** [oliver-zehentleitner/unicorn-binance-websocket-api#147]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ x] Are you using the module on a VPS or other Cloud hosting?
- [ ] Are you using the module on a Raspberry Pi?

#### What kind of internet connection do you have?
My python code run in a Tokyo zone of GCP very close to Binance endpoitn (round trip delay about 5ms)
Include here a description of your internet access like cable, lte and up and download rate.
```

#### Average system load (CPU)
20%
Include here the ammount of cpu cores and the average system load.
```

#### Hardware specification 
```
Include here a description of the server hardware.
```

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [x ] Linux (include flavour)

#### Options
- [ ] stream_buffer
- [x] process_stream_data

#### Which endpoint do you connect?
fapi

Include here the endpint you are connecting to, like binance.com, binance.com-isolated_margin or binance.org-testnet
```

#### Python Version Requirement
- [ ] I am using Python 3.6.1 or above

#### Exact Python Version?
```
Include here the response of 'python --version' AND 'python3 --version'
```

#### Pip Version?
```
Include here the response of 'python3 -m pip --version' or 'pip3 --version'
python:3.6-stretch (dockerized)
```

#### Dependencies
Run `pip list > pip_list.txt` and upload the file.

#### UNICORN Binance WebSocket API Version?
1.28

Did you upgrade to the latest release version with `pip install unicorn-binance-websocket-api --upgrade`?

Please control what version you are using with this script and post the output: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/tools/get_used_module_version.py
```

#### Description of your issue
```
Include the contents of the log file here. (REMOVE API_KEY, API_SECRET, LISTEN_KEY!!)
```

**Comment by amaioli** [comment]
I got this error just one time (9th of february) during UserData streaming

**Comment by oliver-zehentleitner** [comment]
Please provide the logs!

**Comment by oliver-zehentleitner** [comment]
I am not sure but this can also be a result of problems at binance endpoints for example, since it was only one time and then it worked again... did anything happen? If you post me the logs i can see what happend at that time in the lib and for what this request was for.

Did it cause any further errors or problems or restarts?

**Comment by amaioli** [comment]
Unfortunately I hadn't the log open. However I confirm it happens just one time during an high volatility scenario.

**Comment by oliver-zehentleitner** [comment]
important is, did it restart or break the execution?

**Comment by oliver-zehentleitner** [comment]
Please reopen with with a log and more infos.
