### ISSUE TITLE
auto_replace_stream(interval_h=24)

### ISSUE THREAD

**Issue by oliver-zehentleitner** [oliver-zehentleitner/unicorn-binance-websocket-api#15]
If Binance initiate a disconnect and the connection has to be reestablished, does Binance deliver all data since the disconnect or is there a gap? If there is a gap, it could be a solution to replace streams (start a new with same settings and close the old on the first receive of the new stream) every X hours. 

Has anyone analyzed this and can share knowlegde?

**Comment by pisulski** [comment]
From my knowladge they just start a websocket. Mayby Binance API English on telegram help you with answer. I saw only information from users  'oh no after restart my bot doesnt work. Does websocket sent messages?
Probably user Ninj0r from this channel is most adequate.

**Comment by oliver-zehentleitner** [comment]
Thanks for the hint, will do so!

**Comment by oliver-zehentleitner** [comment]
answer: You will miss the data sent while you were disconnected
