### ISSUE TITLE
Basic websocket question

### ISSUE THREAD

**Issue by zwang17** [oliver-zehentleitner/unicorn-binance-websocket-api#152]
I really like this API and it's incredibly convenient! I am very new to websocket and still trying to figure things out. Quick question - after I end a program, does the streaming connection close? Or does it keep running in the background? I am trying things out on Jupyter notebook and created a bunch of BinanceWebSocketApiManager and a bunch of streams, so I am wondering if I need to manually close all steams before shutting down Jupyter notebook or do they get disconnected automatically. Thanks!

**Comment by oliver-zehentleitner** [comment]
If you kill or exit the process which is running the subroutines for websockets its closed too.

As far as I can remember, its enough to close jupyter. You can proof this via a taskmanager....

**Comment by oliver-zehentleitner** [comment]
If need, just reopen!
