### ISSUE TITLE
There are two Binance baseurls for futures 

### ISSUE THREAD

**Issue by E112358** [oliver-zehentleitner/unicorn-binance-websocket-api#153]
Great work... is it possible to include the two different Binance Futures types (USD-M futures and Coin-M futures)?

https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/commit/f68f55b104f40a887fd9febd2040f035903be6b6
188        elif self.exchange == "binance.com-futures":
189        self.websocket_base_uri = "wss://fstream.binance.com/"

The above works for USD-M futures, but for coin futures it should point to: wss://dstream.binance.com

And futures seem to be more popular than regular crypto these days, so maybe you can include this too?

**Comment by oliver-zehentleitner** [comment]
Thanks!

Unfortunately there is more to change than the base URL, it also needs special handling of listenkeys.... 

Continue here: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/134
