### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by thiblab** [oliver-zehentleitner/unicorn-binance-websocket-api#154]
Hello,

I am using your websocket and I'm highly surprised by the ressources needed. I have an i7 CPU and it is used between 20% and 75% !! Only one channel on 3 crypto are streamed so it does not come from this.

Do you have any idea on how to make it lighter ?

![image](https://user-images.githubusercontent.com/34058591/110537996-c098a600-8123-11eb-9bca-aef1d3f04d95.png)

Thanks

**Comment by oliver-zehentleitner** [comment]
Hello!

If you have 8 cores, the lib should be able to use at most 12.5% of your system CPU power (1 core) because of Python GIL.

You also show in the screenshot the system load, not the load of your Python script.

Can you show your code?

Best regards,
Oliver

**Comment by oliver-zehentleitner** [comment]
If you have further questions, just reopen this issue.
