### ISSUE TITLE
Move ubwa logging to new loggers

### ISSUE THREAD

**Issue by xilopaint** [oliver-zehentleitner/unicorn-binance-websocket-api#164]
**Is your feature request related to a problem? Please describe.**
In Python the logging structure is inherited from the root logger. I think the choice of using the root logger for the logging events of a library is not a good practice and makes difficult for developers building their own logging structure.

**Describe the solution you'd like**
Avoid using the root logger and create new loggers for ubwa modules. Here's some [guidelines from Python docs](https://docs.python.org/3/howto/logging.html):

> A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:
> 
> logger = logging.getLogger(__name__)
> This means that logger names track the package/module hierarchy, and it’s intuitively obvious where events are logged just from the logger name.
> 
> The root of the hierarchy of loggers is called the root logger. That’s the logger used by the functions debug(), info(), warning(), error() and critical(), which just call the same-named method of the root logger. The functions and the methods have the same signatures. The root logger’s name is printed as ‘root’ in the logged output.

**Comment by oliver-zehentleitner** [comment]
I would merge a PR

**Comment by oliver-zehentleitner** [comment]
Thanks to @kylematoba for the PR! It will be included in the next release!
