### ISSUE TITLE
Is there a way to get streamed ONLY closed candles off an interval instead of all klines ?

### ISSUE THREAD

**Issue by chromafunk** [oliver-zehentleitner/unicorn-binance-websocket-api#172]
Does Binance.com provides for a way to get streamed down only closed candles instead of getting all klines ?

**Comment by oliver-zehentleitner** [comment]
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_kline_1m_with_unicorn_fy.py#L79
