### ISSUE TITLE
Flickering issue with `print_summary`

### ISSUE THREAD

**Issue by xilopaint** [oliver-zehentleitner/unicorn-binance-websocket-api#174]
I got this annoying issue when using `print_summary`:

![Screen Recording 2021-05-18 at 6 40 53 AM](https://user-images.githubusercontent.com/11052366/118630103-9eb34380-b7a4-11eb-87e8-964d06813165.gif)

I suspected it could have something to do with colorama due to the issues it caused with SwiftBar, but I already tried the new `disable_colorama` parameter with no luck.

**Comment by oliver-zehentleitner** [comment]
As mentioned in Telegram, this often depends from the terminal and its settings (do not use to much cache/history!!!)

Feel free to reopen if needed!
