### ISSUE TITLE
current-average-price

### ISSUE THREAD

**Issue by chocho13** [oliver-zehentleitner/unicorn-binance-websocket-api#177]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I would like get average current price for a symbol avalaible here : 
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#current-average-price

**Describe alternatives you've considered**
Until now I calculate the mean of open_price and close_price of kline1m and calculate over 20 iterations of the previous calculation

**Additional context**
No additional context

Thank you :)

**Comment by oliver-zehentleitner** [comment]
What you want is for REST API: https://github.com/oliver-zehentleitner/unicorn-binance-rest-api

This is the repository for Websocket API.
