### ISSUE TITLE
How to use api1 or api2 or api3 ?

### ISSUE THREAD

**Issue by TKR-US** [oliver-zehentleitner/unicorn-binance-websocket-api#180]
Hello,

i'm new comer on Binance and new comer unicorn library (since 2 days) (come from python-binance, but i've found a random PONG bug).

i've a little problem about latency on api.binance.com (300 ms), but 6 ms on ap1, ap2 or api3.binance.com
On python-binance, i can change url with 
client.API_URL = 'https://api1.binance.{}/api'

Is there a way to have same feature ?

Regards

**Comment by TKR-US** [comment]
I tried something as :
binance_websocket_api_manager = BinanceWebSocketApiManager(exchange="binance.com")
binance_websocket_api_manager.restful_base_uri="https://api1.binance.com"

but this is not the right way... :)

**Comment by oliver-zehentleitner** [comment]
Isnt this just working with REST API?

The only thing we use REST for is managing listenKeys... thats not blocking or speed relevant.

I wanted to write an method for pinging the different endpoints and choosing the fastest one, but i think thats only really usefull for rest api not for websockets...

**Comment by TKR-US** [comment]
mhhh you are right

stream.binance.com for websocket, and there is only this url (and 300 ms for me :( )
I am not sure that there is a huge interest in making an improvement in this direction

**Comment by oliver-zehentleitner** [comment]
most people i know compensate this with servers localy close to binance dc. on telegram channel was some discussions about this in the past and sharing experience about this topic...

**Comment by TKR-US** [comment]
Mhh
they use Amazon DC, as binance?
I am on German DC (physical servers)
