### ISSUE TITLE
Question about specific Line code - Error 1006

### ISSUE THREAD

**Issue by TKR-US** [oliver-zehentleitner/unicorn-binance-websocket-api#181]
Hello,

After a discussion with @Zakariaair, i've a question about this line :
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/e4146d4c352bd0b8a9c1cb18d960de89235e943b/unicorn_binance_websocket_api/unicorn_binance_websocket_api_socket.py#L181

Is this supposed to correct a PONG problem that sometimes happens (a bug encountered on another library), or has this been implemented to handle reconnection after 24 hours?

Regards

**Comment by oliver-zehentleitner** [comment]
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/113

**Comment by TKR-US** [comment]
Thanks for this reply and this thread, it's clear now for me.
