### ISSUE TITLE
How delete log on BinanceWebSocketApiProcessStreams?

### ISSUE THREAD

**Issue by rOMA2222** [oliver-zehentleitner/unicorn-binance-websocket-api#191]
I can't remove the work log. Is there a way to remove print()

**Comment by oliver-zehentleitner** [comment]
Yes, you can controll the logging module with such a code:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/e30f6bd036bd6f3d6110c682c1bce4f185ed1172/example_binance_coin_futures.py#L46

**Comment by oliver-zehentleitner** [comment]
Feel free to reopen if needed!
