### ISSUE TITLE
Futures socket does not work with websockets version 10.0

### ISSUE THREAD

**Issue by June911** [oliver-zehentleitner/unicorn-binance-websocket-api#196]
I was trying to subscribe to the future data on my AMS EC2. The streams seemed to be created successfully but I didn't receive any stream data. 

![Screen Shot 2021-09-18 at 1 39 04 PM](https://user-images.githubusercontent.com/54600570/133878425-1f8cc5e0-7cc2-4c46-b3b6-aa71dbb6706a.png)

Thanks to [DaStapo](https://github.com/sammchardy/python-binance/issues/1023), I tried to downgrade "websockets==10.0" to "websockets==9.1". It finally worked. For those who experience the same issue, try it. 

To reproduce:
- Lasted unicorn-binance-websocket-api package
- "websockets==10.0"
- Run "example_binance_futures.py"

Environment:
- Python 3.8.10
- Ubuntu

**Comment by oliver-zehentleitner** [comment]
I dont understand the setup.
The latest UBWA version is using websockets==9.1 ... there is no package released with 10.0, only a pull request: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/pull/195

**Comment by June911** [comment]
Ahh, ok. I didn't know how to run the setup, so I installed the packages one by one. When I installed WebSockets, its default version is 10.0. Then, I got the issue. 

Thanks for your response. I checked online and I know how to install packages according to requirements.

**Comment by oliver-zehentleitner** [comment]
hm, i testet websockets 10 with ubwa and it works ...
