### ISSUE TITLE
How to get https://binance-docs.github.io/apidocs/futures/en/#user-data-streams

### ISSUE THREAD

**Issue by Lifr0m** [oliver-zehentleitner/unicorn-binance-websocket-api#201]
Hi! I need access for user data stream (like order updating). I changed leverage, posted orders but nothing in the output. What am I doing wrong?
[code](https://pastebin.com/dLzpi8MQ)
[output](https://pastebin.com/RRrmysGS)

**Comment by oliver-zehentleitner** [comment]
i think this is related to: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/199

just use version [1.33.1](https://pypi.org/project/unicorn-binance-websocket-api/1.33.1/) till this issue is fixed!

**Comment by Lifr0m** [comment]
> i think this is related to: #199
> 
> just use version [1.33.1](https://pypi.org/project/unicorn-binance-websocket-api/1.33.1/) till this issue is fixed!

Wow! It's working! Thanks man!
