### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dima-dmytruk23** [oliver-zehentleitner/unicorn-binance-websocket-api#205]
Hi. We are using Python3.8, websocket-client==1.1.1, websockets==9.1, unicorn-binance-websocket-api==1.31.0

We receive about 600 data objects every 250 ms.

We are constantly faced with the problem of memory leaks.

The specifics of our service:
Every 50 minutes we close the old websocket and open a new websocket. Maybe we are doing it incorrectly?
```
    def toggle_websockets(self, last_time):
        if not self.websockets1:
            for markets in markets_list:
                twm = BinanceWebSocketApiManager(
                    exchange="binance.com-futures",
                    warn_on_update=False,
                )
                stream = twm.create_stream(
                    tuple(channels), tuple(markets)
                )
                self.websockets1.append((twm, stream))

            for ws in self.websockets2:
                ws[0].stop_manager_with_all_streams()
            self.websockets2 = []

        else:
            for markets in markets_list:
                twm = BinanceWebSocketApiManager(
                    exchange="binance.com-futures",
                    warn_on_update=False,
                )
                stream = twm.create_stream(
                    tuple(channels), tuple(markets)
                )
                self.websockets2.append((twm, stream))

            for ws in self.websockets1:
                ws[0].stop_manager_with_all_streams()
            self.websockets1 = []
```

`tracemalloc` show to this.
```
/usr/local/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 834
    return frame.data.decode("utf-8") if text else frame.data
```

**Comment by oliver-zehentleitner** [comment]
Are you creating one stream for each market symbol?

**Comment by oliver-zehentleitner** [comment]
Why did you close it?

**Comment by dima-dmytruk23** [comment]
@oliver-zehentleitner There was a bug in my implementation. In each iteration, I created a new manager and a separate stream to it. As a result, the stream buffer filled up (only the last stream was cleared). The memory leak issue is almost over. There is a small accumulation (in the `legacy protocol on the websockets` and `self.encoder = zlib.compressobj(` in ` websockets/extensions/permessage_deflate.py`), of course, but now it is not critical.
