### ISSUE TITLE
COINM Futures AggTrade doesnt work

### ISSUE THREAD

**Issue by Indiana3714** [oliver-zehentleitner/unicorn-binance-websocket-api#208]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [X] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] Are you using the module on a Raspberry Pi?
- [X] On my local computer

#### What kind of internet connection do you have?
```
Fiber
```

#### Average system load (CPU)
```
Include here the ammount of cpu cores and the average system load.
```

#### Hardware specification 
```
Include here a description of the server hardware.
```

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)

#### Options
- [X] stream_buffer
- [ ] process_stream_data

#### Which endpoint do you connect?
```
binance.com-coin-futures
```

#### Python Version Requirement
- [X] I am using Python 3.7 or above

#### Exact Python Version?
```
3.9.7
```

#### Pip Version?
```
pip21.3
```

#### Dependencies
Run `pip list > pip_list.txt` and upload the file.

#### UNICORN Binance WebSocket API Version?
```
Did you upgrade to the latest release version with `pip install unicorn-binance-websocket-api --upgrade`?

Please control what version you are using with this script and post the output: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/tools/get_used_module_version.py
```

#### Description of your issue
```
[example_binance_coin_futures.py.log](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/7364338/example_binance_coin_futures.py.log)
```

After cloning your master branch yesterday, I've used your example "example_binance_coin_futures.py" and commented out lines 64 to 74 and 79 to 83. (This leaves aggTrade being the only channel subscribed)

Here's the summary after 1 minute, (no packets are ever received):

```
==================== unicorn-binance-websocket-api_1.34.1.dev-python_3.9.7 ====================
 exchange: binance.com-coin-futures
 uptime: 1m:1s since 2021-10-18, 11:12:24 UTC
 streams: 1
 active_streams: 1
 subscriptions: 3
 current_receiving_speed: 0 B/s
 average_receiving_speed: 0.0 B/s (per day 0.0 gB)
 highest_receiving_speed: 0 B/s (reached at 2021-10-18, 11:12:24 UTC)
 total_receives: 0
 total_received_bytes: 0 (0 B)
 total_transmitted_payloads: 1
 stream_buffer_maxlen: None
 process_ressource_usage: cpu=11.2%, memory=47.76 mB, threads=6
 ---------------------------------------------------------------------------------------------
               stream_id              |   stream_label  |  last  |  average  |  peak  | recon
 ---------------------------------------------------------------------------------------------
 5ca08a9a-5fec-4ff1-a05e-6b4b0e927e40 | None            |      0 |       0.0 |      0 |      0
 ---------------------------------------------------------------------------------------------
 all_streams                                            |      0 |       0.0 |      0 |      0
===============================================================================================```

**Comment by oliver-zehentleitner** [comment]
for sure it is, i know the issue on python-binance.

we are doing the same. i think till ubwa 1.33.1 we used websockets 9.1 and i swapped to websockets 10.0 with 1.34.0. then we recognized this bug, reported it to websocket libs and they found out an issue in binance and AWS api gateway and they reported it to AWS and i reported it to binance. binance confirmed the issue and is planing to release an update on their futures api in the end of october 2021. then the new "optimization feature" (which is provocation this bug) will be supported by binance and we can use it. till then i disabled the new feature of websockets 10.0 in ubwa for future endpoints. i will release 1.34.2 soon with a fix for coin-futures and  websockets 10.0.
