### ISSUE TITLE
Option to daemonize threads

### ISSUE THREAD

**Issue by BananaLoaf** [oliver-zehentleitner/unicorn-binance-websocket-api#212]
**Is your feature request related to a problem? Please describe.**
Program refuses to close on SIGTERM even if there are no active data streams

**Describe the solution you'd like**
Class [BinanceWebSocketApiManager](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py#L63) should have daemon functionality. Same could be applied to [data streams](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py#L1211)

**Comment by oliver-zehentleitner** [comment]
You can use catch the signal in your script and call [`ubwa.stop_manager_with_all_streams()`](https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html?highlight=stop_manager#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.stop_manager_with_all_streams)

**Comment by oliver-zehentleitner** [comment]
Just reopen if you have further questions
