### ISSUE TITLE
What is the best way to add delay to data streams?

### ISSUE THREAD

**Issue by serteikas** [oliver-zehentleitner/unicorn-binance-websocket-api#215]
I have high CPU usage, I would want to receive updates every 5 seconds (as an example) instead of default values.

What would be the best way to achieve this?

**Comment by oliver-zehentleitner** [comment]
What Info do you want to receive?

**Comment by serteikas** [comment]
> What Info do you want to receive?

```
TICKERS = ["BTCUSDT". "ETHUSDT"]
ubwa = BinanceWebSocketApiManager(exchange="binance.com")
ubwa.create_stream(['ticker'], TICKERS, output="UnicornFy")
```

**Comment by dima-dmytruk23** [comment]
@serteikas You can create a variable in which you will store the time when the last data was received and, based on this variable, calculate the delta to process the following data.

**Comment by oliver-zehentleitner** [comment]
if you receive ticker for 2 symbols that is very less data...

As far as I know, you can not slow down the sending interval for tickers by Binance, so you have to manage this in your algo.

If you want to receive the latest info every 5 seconds, you can use the stream_buffer as a LIFO stack and a small maxlenght. 
That way each time you access the stream_buffer, you will receive the latest information and use time.sleep(4) till you pick up the next record from the stream_buffer.

Ticker is sent each 1000 ms. so you can throw 4 records away and then you process one (in a loop).
