### ISSUE TITLE
using UBWA to execute futures trades on Binance

### ISSUE THREAD

**Issue by djangoengine** [oliver-zehentleitner/unicorn-binance-websocket-api#217]
I have been using python-binance api for few months however having lot's of issues executing futures trade and also had issue with their websocket api. 
so I looked at other options and UBWA seems very good and robust.
I wonder whether

**Comment by djangoengine** [comment]
Oh I noted you have rest-api too.

**Comment by oliver-zehentleitner** [comment]
websockets does not excecute anything... use https://github.com/oliver-zehentleitner/unicorn-binance-rest-api
