### ISSUE TITLE
[Question] How to set network proxy?

### ISSUE THREAD

**Issue by inix** [oliver-zehentleitner/unicorn-binance-websocket-api#219]
Hi:
The Binance domains are blocked in some area, how to set network proxy if using this lib?
Thanks

**Comment by oliver-zehentleitner** [comment]
I never tried, but you can find infos here:
https://github.com/aaugustin/websockets/issues/364
https://github.com/aaugustin/websockets/issues/475

**Comment by inix** [comment]
No progress from these two issues.

> I never tried, but you can find infos here: [aaugustin/websockets#364](https://github.com/aaugustin/websockets/issues/364) [aaugustin/websockets#475](https://github.com/aaugustin/websockets/issues/475)

**Comment by oliver-zehentleitner** [comment]
are you able to setup a proxy in your os or gateway?

**Comment by inix** [comment]
> are you able to setup a proxy in your os or gateway?

I have http and socks proxy setup in my MacOS, but I am not familar with Python, nodejs websocket 'ws' have proxy module, I heve tested successfully using Binance Official websocket codes.

**Comment by oliver-zehentleitner** [comment]
ok i understand!

**Comment by wisfern** [comment]
> > are you able to setup a proxy in your os or gateway?
> 
> I have http and socks proxy setup in my MacOS, but I am not familar with Python, nodejs websocket 'ws' have proxy module, I heve tested successfully using Binance Official websocket codes.

how to do?
