### ISSUE TITLE
How can I subscribe to different channels for different symbols?

### ISSUE THREAD

**Issue by am11y** [oliver-zehentleitner/unicorn-binance-websocket-api#220]
Hello, 
if I create a stream:

stream_id = binance_websocket_api_manager.create_stream( 'bnbbtc', 'kline_1m' )

and then 

binance_websocket_api_manager.subscribe_to_stream( stream_id, channels = 'kline_5m', markets = 'batbtc' )

Then I get 4 different subscriptions:
bnbbtc @ 1m
bnbbtc @ 5m
batbtc @ 1m
batbtc @ 5m

 and not 2, as I would expect.
bnbbtc @ 1m
batbtc @ 5m

Why is that? How can I get two subscriptions and not criss-cross of all channels and symbols?

**Comment by oliver-zehentleitner** [comment]
Thats the way it works: https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.create_stream
