### ISSUE TITLE
[Question] Get raw data via rest server.

### ISSUE THREAD

**Issue by nagualcode** [oliver-zehentleitner/unicorn-binance-websocket-api#36]
Hello, 
First I would like yo thank you Oliver, for this great project.

I am paving my way into Python CS, so forgive me if this is a non-sense question.

I see the monitoring example, where it runs a local rest server, and I wonder, If I could serve json, for example, kline 1h, to other services that request it locally, via this rest server.

Thank you!

**Comment by oliver-zehentleitner** [comment]
Hello!

No its not possible to forward messages through the REST server. Its only purpose is delivering infos about the status of the library to a monitoring system.

More info about the REST server is here: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/UNICORN-Monitoring-API-Service

Best regards,
Oliver
