### ISSUE TITLE
*** IMPORTANT TO KNOW: Changes in release 1.10.0 ***

### ISSUE THREAD

**Issue by oliver-zehentleitner** [oliver-zehentleitner/unicorn-binance-websocket-api#38]
Hello!

In the releases 1.10.0 i added subscriptions through websocket.send() which enables the lib to subscribe on demand: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#live-subscribingunsubscribing-to-streams

In all versions of this lib <= 1.9.x the subscriptions got handled within create_stream() via the URI on websocket.connect(), to change markets or channels it was necessary to use [replace_stream()](binance). Now its possible to [subscribe](https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.subscribe_to_stream) and [unsubscribe](url) on demand via [subscribe_to_stream()](https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.subscribe_to_stream) and [unsubscribe_from_stream()](https://oliver-zehentleitner.github.io/unicorn-binance-websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.unsubscribe_from_stream). 

A very nice benefit is, we can bypass the 8004 char limit in the URI for subscriptions which makes [is_websocket_length_valid()](https://oliver-zehentleitner.github.io/unicorn--websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.replace_stream) obsolete and makes also the request https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/19 (virtual stream interface) unnecessary! 

Beginning with 1.10.0 [is_websocket_length_valid()](https://oliver-zehentleitner.github.io/unicorn--websocket-api/unicorn_binance_websocket_api.html#unicorn_binance_websocket_api.unicorn_binance_websocket_api_manager.BinanceWebSocketApiManager.replace_stream) will always return `True`!

## The most important part now
As a result of this changes the endpoints are answering with a new message that looks like:
```
{"result":null,"id":1}
{"result":null,"id":2}
{"result":null,"id":3}
{"result":null,"id":4}
```
Its possible that this is crashing your script ...

Have fun!

Best regards,
Oliver

Edit 2020-04-28:
There is a new limit of 1024 subscriptions per stream: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/45#issuecomment-619419025

**Comment by officialnico** [comment]
hey man i keep getting this error {"result":null,"id":1} and so on. i saw you mentioned it but im not sure how to fix it?

**Comment by oliver-zehentleitner** [comment]
its NOT an error! 

Please read here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#live-subscribingunsubscribing-to-streams
