### ISSUE TITLE
[question] swap markets, and past 200 klines

### ISSUE THREAD

**Issue by nagualcode** [oliver-zehentleitner/unicorn-binance-websocket-api#41]
Hello!
I am hacking the examples.. While learning about Python. I am looking to get klines from the btcusd **Swap** market.
This is what I came up:
binance_websocket_api_manager.create_stream(["kline_4h"], markets)

With this I can get 1 json object with the most recent kline at first, and then the streaming goes on with new knlines... But how could I get the past 200 klines at once?

Also, is this the swap market?
BinanceWebSocketApiManager(exchange="binance.com-futures")

Thank you!

**Comment by oliver-zehentleitner** [comment]
hi nagualcode!

be aware that you get klines_4 in the beginning of the 4 hours frame, during the 4 hours and when the 4 hours end. Just save the last kline with an `event_time` later than the `kline_close_time`. Look here for an example: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/43e5625ebe9c006c3e3224b53597e60a5df76545/example_kline_1m.py#L76

With ws its not possible to get "old" data. If you want that, you have to use REST API with `python-binance`or `ccxt`.

What exactly is swap market? On binance you see a `spot`, `margin` and `futures` account. to use `spot`you have to use `binance.com`. 

Best regards,
Oliver
