### ISSUE TITLE
Conflict with python-binance package (ImportError)

### ISSUE THREAD

**Issue by am11y** [oliver-zehentleitner/unicorn-binance-websocket-api#46]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [X ] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ ] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?
- [ ] Are you using the module on a Raspberry Pi?

#### Operating System? (include version)
- [ ] macOS
- [X] Windows
- [ ] Linux (include flavour)

#### Python Version Requirement
- [X] I am using Python 3.5.3 or above

#### Exact Python Version?
```
Python 3.8.2
``

#### Pip Version?
```
pip 20.0.2
```

#### Dependencies
Run `pip list > pip_list.txt` and upload the file.

#### UNICORN Binance WebSocket API Version?
```
Did you upgrade to the latest release version with `pip install unicorn-binance-websocket-api --upgrade`?

Please control what version you are using with this script and post the output: 1.11.0
```

#### Description of your issue

```
Hello Oliver, as I found you here I would like to ask you for help. If I use your unicorn-binance-websocket-api together with sammchardy's python-binance, then I get ImportError:

site-packages\unicorn_binance_websocket_api\unicorn_binance_websocket_api_connection.py", line 36, in <module>
    from websockets import connect
ImportError: cannot import name 'connect' from 'websockets' 

Please help, I can only get both running by removing sammchardy's library from Python PATH before calling imports:
sys.path.remove(pytonInstallFolder + "\\Python38\\Lib\\site-packages\\binance")

```
[pip_list.txt](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/4448580/pip_list.txt)

**Comment by oliver-zehentleitner** [comment]
Hello!

Sorry for long waiting.

To be honest, I dont know what is happening in your case, but here is a script using both libs together, maybe it helps you: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_stream_everything.py

if you need my help, i would need more infos, maybe you can post a script that is dropping the error?

Best regards,
Oliver

**Comment by oliver-zehentleitner** [comment]
If you still need help, please reopen this issue. thanks!
