### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by jemeraldo** [oliver-zehentleitner/unicorn-binance-websocket-api#47]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [ ] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [ x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [ x] Are you using the module on a VPS or other Cloud hosting?
- [ ] If so, have you tried running the code on your local machine?
- [ ] Are you using the module on a Raspberry Pi?

#### Operating System? (include version)
- [ ] macOS
- [ ] Windows
- [ x] Linux (include flavour)

#### Python Version Requirement
- [x ] I am using Python 3.5.3 or above

#### Exact Python Version?
```
Include here the response of 'python --version' or 'python3 --version'
```
Python 3.7.3

#### Pip Version?
```
Include here the response of 'pip --version' or 'pip3 --version'
```
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
#### Dependencies
Run `pip list > pip_list.txt` and upload the file.
Package                       Version
----------------------------- ----------
aniso8601                     8.0.0
APScheduler                   3.6.3
attrs                         19.3.0
autobahn                      20.3.1
Automat                       20.2.0
certifi                       2019.11.28
cffi                          1.14.0
chardet                       3.0.4
chart-studio                  1.0.0
cheroot                       8.3.0
click                         7.1.1
colorama                      0.4.3
constantly                    15.1.0
cryptography                  2.8
dateparser                    0.7.4
decorator                     4.4.2
Flask                         1.1.1
Flask-RESTful                 0.3.8
future                        0.18.2
hyperlink                     19.0.0
idna                          2.9
incremental                   17.5.0
itsdangerous                  1.1.0
jaraco.functools              3.0.0
Jinja2                        2.11.1
lxml                          4.5.0
MarkupSafe                    1.1.1
more-itertools                8.2.0
numpy                         1.18.1
pandas                        1.0.2
pandas-datareader             0.8.1
pathlib                       1.0.1
pip                           20.0.2
plotly                        4.5.4
psutil                        5.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
PyHamcrest                    2.0.2
pymongo                       3.10.1
pyOpenSSL                     19.1.0
python-binance                0.7.5
python-dateutil               2.8.1
python-telegram-bot           12.4.2
pytz                          2019.3
regex                         2020.2.20
requests                      2.23.0
retrying                      1.3.3
service-identity              18.1.0
setuptools                    40.8.0
six                           1.14.0
tinydb                        3.15.2
tornado                       6.0.4
Twisted                       20.3.0
txaio                         20.1.1
tzlocal                       2.0.0
ujson                         2.0.1
unicorn-binance-websocket-api 1.11.0
unicorn-fy                    0.3.3
urllib3                       1.25.8
websocket-client              0.57.0
websockets                    8.1
Werkzeug                      1.0.0
zope.interface                5.0.1
#### UNICORN Binance WebSocket API Version?
```
Did you upgrade to the latest release version with `pip install unicorn-binance-websocket-api --upgrade`?

Please control what version you are using with this script and post the output: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/tools/get_used_module_version.py
```
1.11.0

#### Description of your issue

```
Include the contents of the log here (if applicable). < REPLACE THIS TEXT
```

> Apr 18 23:14:20 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:19 - INFO - BinanceWebSocketApiManager->_keepalive_streams() new instance created with keepalive_streams_id=1587251659.8523495
> Apr 18 23:14:20 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:20 - INFO - BinanceWebSocketApiManager->_keepalive_streams() new instance created with keepalive_streams_id=1587251660.30247
> Apr 18 23:14:20 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:20 - INFO - BinanceWebSocketApiManager->_keepalive_streams() found an other living instance, so i stop1587251660.30247
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]: Exception in thread Thread-152:
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]: Traceback (most recent call last):
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:   File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:     self.run()
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:   File "/usr/local/lib/python3.7/threading.py", line 865, in run
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:     self._target(*self._args, **self._kwargs)
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:   File "/home/admin/bb-release/env/lib/python3.7/site-packages/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py", line 381, in _frequent_checks
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]:     for keepalive_streams_id in self.keepalive_streams_list:
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]: RuntimeError: dictionary changed size during iteration
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:22 - INFO - BinanceWebSocketApiManager->_keepalive_streams() new instance created with keepalive_streams_id=1587251662.3900542
> Apr 18 23:14:22 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:22 - INFO - BinanceWebSocketApiManager->_keepalive_streams() found an other living instance, so i stop1587251662.3900542
> Apr 18 23:14:42 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:42 - CRITICAL - BinanceWebSocketApiSocket->start_socket(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Exception ConnectionClosed Info: code = 1006 (connection closed abnormally [internal]), no reason
> Apr 18 23:14:42 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:42 - CRITICAL - BinanceWebSocketApiManager->stream_is_crashing(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a)
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->restart_stream(['aggTrade'], ['btcusdt'])
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->restart_stream(['aggTrade'], ['btcusdt'])
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->restart_stream(['aggTrade'], ['btcusdt'])
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 50}]
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 51}]
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 52}]
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->restart_stream(['aggTrade'], ['btcusdt'])
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 53}]
> Apr 18 23:14:43 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:43 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:14:44 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:44 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 55}]
> Apr 18 23:14:44 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:44 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:14:44 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:44 - INFO - BinanceWebSocketApiManager->create_payload(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Payload: [{'method': 'SUBSCRIBE', 'params': ['btcusdt@aggTrade'], 'id': 54}]
> Apr 18 23:14:44 ip-172-26-4-75 python3[12623]: 2020-04-18 23:14:44 - INFO - Created websocket URI for stream_id=1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a is wss://stream.binance.com:9443/stream?streams=btcusdt@aggTrade
> Apr 18 23:32:29 ip-172-26-4-75 python3[12623]: 2020-04-18 23:32:25 - INFO - BinanceWebSocketApiManager->_frequent_checks() new instance created with frequent_checks_id=1587252745.3812144
> Apr 18 23:32:35 ip-172-26-4-75 python3[12623]: 2020-04-18 23:32:32 - INFO - sent listen_key keepalive ping for stream_id=bf88a25d-8e74-4490-b631-2ddc53d9ce02
> Apr 18 23:32:38 ip-172-26-4-75 python3[12623]: 2020-04-18 23:32:32 - INFO - sent listen_key keepalive ping for stream_id=bf88a25d-8e74-4490-b631-2ddc53d9ce02
> Apr 18 23:32:38 ip-172-26-4-75 python3[12623]: 2020-04-18 23:32:33 - INFO - BinanceWebSocketApiManager->_frequent_checks() new instance created with frequent_checks_id=1587252753.7786205
> 
[log.log](https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/files/4498732/log.log)

Maybe it need:
`for keepalive_streams_id in list(self.keepalive_streams_list):`

**Comment by jemeraldo** [comment]
Also, I'm facing with many disconnects like this:

> Apr 18 22:43:50 ip-172-26-4-75 python3[12623]: 2020-04-18 22:43:50 - CRITICAL - BinanceWebSocketApiSocket->start_socket(1f77b3c5-8e45-46f2-8d84-9dbaa7cc4f5a, ['aggTrade'], ['btcusdt']) Exception ConnectionClosed Info: code = 1006 (connection closed abnormally [internal]), no reason

Can it be the result of 14 Apr changes in Binance Futures API? And how we can handle it?

> WEB SOCKET STREAM
> 
> There is now a 5 requests/second restriction when connecting/disconnecting and/or sending messages to the web socket.
> This means you can send in 5 messages per second into the websocket. (e.g. subscribing/unsubscribing, PING/PONG, etc.)
> If a user sends too many requests, they may be disconnected and/or possibly banned.
> There is also a max limit of streams that can be subscribed to. The max is 1024 streams.

**Comment by oliver-zehentleitner** [comment]
Hi Jemeraldo!
Thanks for the report.
1. The first issue is easy to fix, just need to add a threadding.lock().
2. connection closed abnormally is a network/pc problem in most cases. On server in good datacenters I have zero of them, at home many per day...
Anyway, I guess you are right with the update from 14.4.2020. I will add a handling for this, atm we are hammering all subscriptions at one time and dont care about the max of 1024 streams.
Will try to fix this in the next week!
Best regards,
Oliver

PS. Please create one issue for each bug/topic: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Issue-Guidelines

**Comment by oliver-zehentleitner** [comment]
Hi Jemeraldo,!

1. is fixed now

I close this issue, lets continue the discussion of 2. in  issue https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/45 - its seems to be related.

Best regards,
Oliver
