### ISSUE TITLE
Wrong stream_buffer_byte_size calculation

### ISSUE THREAD

**Issue by DaWe35** [oliver-zehentleitner/unicorn-binance-websocket-api#51]
I don't know, how `stream_buffer_byte_size` calculated, but I think it shows wrong value.
I received 1155656 packets (1.25 GB), but 496316 item is in the buffer.
![kép](https://user-images.githubusercontent.com/10603822/80845309-18fc3e80-8c09-11ea-866f-94f32b629faa.png)
496316 / 1155656 = 0.429, so 42% of my packets are in the buffer.
1250 MB * 0.429 = 536 MB, so the real buffer size is around 536 MB. I checked `top`, and it says the python script uses ~600 MB RAM, so my calculation could be good.

- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help
- [ ] Other

#### Environment
- [x] Are you using the module on a VPS or other Cloud hosting?
- [x] If so, have you tried running the code on your local machine?
- [ ] Are you using the module on a Raspberry Pi?

#### Operating System? (include version)
- [ ] macOS
- [x] Windows
- [x] Linux

#### Python Version Requirement
- [x] I am using Python 3.5.3 or above

**Comment by oliver-zehentleitner** [comment]
Its done here https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/unicorn_binance_websocket_api_manager.py#L1456

I will take a look at it! Thank you!
