### ISSUE TITLE
result: none

### ISSUE THREAD

**Issue by DaWe35** [oliver-zehentleitner/unicorn-binance-websocket-api#54]
I'm getting a lot of None, is it a Binance bug or what?
![kép](https://user-images.githubusercontent.com/10603822/80891898-4c050780-8cc7-11ea-9090-8188a3b904a3.png)

Mp4 video: https://siasky.net/AAB8lkszJTBBkgFNMSXqlkUZO7sRAxjXtBn6cmPJtU849A

**Comment by oliver-zehentleitner** [comment]
Its not a bug, its an answer of the subscription messages (confirmed by `id`.

https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/issues/38
https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#subscribe-to-a-stream

I created a telegram group, maybe its better for some kind of communication.
https://t.me/unicorndevs
