### ISSUE TITLE
I cannot install the package

### ISSUE THREAD

**Issue by Dope-K** [oliver-zehentleitner/unicorn-binance-websocket-api#56]
I tried to install the package using <pip install unicorn-binance-websocket-api --upgrade>.
I got error message like

Building wheels for collected packages: ujson
  Building wheel for ujson (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Anaconda3\python.exe' 'C:\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\user\AppData\Local\Temp\tmpsxj4hqn3'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-gtqln2ol\ujson
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
  Running setup.py clean for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

I installed Visualstudio as mentioned in this message. However same error keeps pop up.
How can I solve this problem?
thanks

**Comment by oliver-zehentleitner** [comment]
Try this https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/wiki/Installation

**Comment by oliver-zehentleitner** [comment]
Uh, didnt read all the text :dagger: 

you are on Windows and the error suggests what to do:
Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

**Comment by Dope-K** [comment]
Oh I missed <Get it with "Build Tools for Visual Studio">
Thanks guru! I successfully installed it. 
Thanks a lot

**Comment by oliver-zehentleitner** [comment]
Your welcome!
