### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by benzkji** [oliver-zehentleitner/unicorn-binance-websocket-api#71]
I dont get why it needs flask and other strange packages (itsdangerous...?)...maybe it would help to

1. clearly specify dependencies in the readme
2. put monitoring and other "gadgets" into contrib or other packages, so the main thing needs only the bare minimum of dependencies

what do you think?

**Comment by oliver-zehentleitner** [comment]
Hi benzkji!

flask for example gets installed on the system with the installation (user friendly) and gets only loaded/imported if you start the server: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/unicorn_binance_websocket_api/unicorn_binance_websocket_api_restserver.py

So I guess its not insecure if you dont start the lib on your own and its the most uncomplicated way to ship all at once.

The list to the dependencies is linked here: https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api#description

Best regards,
Oliver

**Comment by benzkji** [comment]
yes, it's about maintenance, etc. the less the better ;-)
