### ISSUE TITLE
How to stream - https://binance-docs.github.io/apidocs/futures/en/#event-order-update

### ISSUE THREAD

**Issue by lucky-ali** [oliver-zehentleitner/unicorn-binance-websocket-api#95]
Hello, 

How can i stream my account inforamtion and get the event-order-update steam?

https://binance-docs.github.io/apidocs/futures/en/#event-order-update

I would like to know when an order is placed, updated or closed. 

Sorry for the noob question.

**Comment by oliver-zehentleitner** [comment]
Hi!
Take a look here:
https://github.com/oliver-zehentleitner/unicorn-binance-websocket-api/blob/master/example_userdata_stream.py
Then trigger some events and see what you receive... 
Best regards,
Oliver

**Comment by lucky-ali** [comment]
Hello,

I have followed the code that you mentioned and i am getting the data in the screenshots below. I placed a couple of orders on my futures account and nothing showed up in the stream any help would be appreciated. 


Code:
![image](https://user-images.githubusercontent.com/20534354/90244687-27bdd880-de29-11ea-88b5-1c2cf40a2f77.png)

Output: 
![image](https://user-images.githubusercontent.com/20534354/90244638-11178180-de29-11ea-90a2-2798fa7587e0.png)

**Comment by oliver-zehentleitner** [comment]
Try `exchange="binance.com-futures"`

**Comment by lucky-ali** [comment]
Perfect that worked. Thanks alot.

**Comment by oliver-zehentleitner** [comment]
Your welcome!
